package ru.kpfu.itis.voicescom.dto;

public enum Status {
    SIGN_UP_SUCCESS,
    SIGN_UP_INVALID_DATE_FORMAT,
    SIGN_UP_USER_ALREADY_EXISTS,
    SIGN_UP_INVALID_DATA,

    SIGN_IN_SUCCESS,
    SIGN_IN_USER_NOT_VERIFIED,
    SIGN_IN_INVALID_DATA,

    ORDER_ADD_ALREADY_EXISTS,
    ORDER_ADD_INVALID_DATA,
    ORDER_ADD_SUCCESS,

    ORDER_VERIFY_ORDER_NOT_FOUND,
    ORDER_VERIFY_INVALID_DATA,
    ORDER_VERIFY_VERIFY_SUCCESS,
    ORDER_VERIFY_UNVERIFY_SUCCESS,

    PROPOSAL_ADD_ALREADY_EXISTS,
    PROPOSAL_ADD_ORDER_NOT_FOUND,
    PROPOSAL_ADD_SUCCESS,

    PROPOSAL_UPDATE_PROPOSAL_NOT_FOUND,
    PROPOSAL_UPDATE_INVALID_DATA,
    PROPOSAL_UPDATE_DENIED,
    PROPOSAL_UPDATE_SUCCESS,

    RECORDING_ADD_ALREADY_EXISTS,
    RECORDING_ADD_ORDER_NOT_FOUND,
    RECORDING_ADD_DENIED,
    RECORDING_ADD_SAVING_ERROR,
    RECORDING_ADD_SUCCESS,

    ORDER_VOICE_DENIED,
    ORDER_VOICE_ERROR,
    ORDER_VOICE_ORDER_NOT_FOUND,
    ORDER_VOICE_ZERO_RECORDINGS,
    ORDER_VOICE_SUCCESS
}